
image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - mkdir -p public
  - hugo --baseURL https://miro.adamy.gitlab.io/miroadamy.com/
  artifacts:
    paths:
    - public
  only:
  - gitlab-pages